import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";

const prod = process.argv[2] === "production";

async function main() {
  const context = await esbuild.context({
    banner: { js: "/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */" },
    entryPoints: ["main.tsx"],
    bundle: true,
    external: [
      "obsidian",
      "electron",
      "@codemirror/autocomplete",
      "@codemirror/collab",
      "@codemirror/commands",
      "@codemirror/language",
      "@codemirror/lint",
      "@codemirror/search",
      "@codemirror/state",
      "@codemirror/view",
      "@lezer/common",
      "@lezer/highlight",
      "@lezer/lr",
      ...builtinModules,
    ],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
    minify: prod,
  });

  if (prod) {
    await context.rebuild();
    await context.dispose();
  } else {
    await context.watch();
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
